version: '3.3'
services:
  nginx:
    image: nginx
    ports:
      - 443:443
      - 3000:3000
      - 80:80
    working_dir: /app
    volumes:
      - ./app:/app
      - ./nginx:/etc/nginx/conf.d
      - ./certificates:/etc/nginx/certs
